export const CONSTITUENCIES = [
  {
    region: 'WESTERN',
    code: 'A0101',
    name: 'JOMORO',
    voters: 92557,
  },
  {
    region: 'WESTERN',
    code: 'A0201',
    name: 'ELLEMBELE',
    voters: 73099,
  },
  {
    region: 'WESTERN',
    code: 'A0301',
    name: 'EVALUE AJOMORO GWIRA',
    voters: 48900,
  },
  {
    region: 'WESTERN',
    code: 'A0401',
    name: 'AHANTA WEST',
    voters: 78323,
  },
  {
    region: 'WESTERN',
    code: 'A0501',
    name: 'TAKORADI',
    voters: 64519,
  },
  {
    region: 'WESTERN',
    code: 'A0502',
    name: 'SEKONDI',
    voters: 44278,
  },
  {
    region: 'WESTERN',
    code: 'A0503',
    name: 'ESSIKADU-KETAN',
    voters: 69125,
  },
  {
    region: 'WESTERN',
    code: 'A0601',
    name: 'EFFIA',
    voters: 52069,
  },
  {
    region: 'WESTERN',
    code: 'A0602',
    name: 'KWESIMINTIM',
    voters: 49764,
  },
  {
    region: 'WESTERN',
    code: 'A0701',
    name: 'SHAMA',
    voters: 60388,
  },
  {
    region: 'WESTERN',
    code: 'A0801',
    name: 'WASSA EAST',
    voters: 54787,
  },
  {
    region: 'WESTERN',
    code: 'A0901',
    name: 'MPOHOR',
    voters: 29294,
  },
  {
    region: 'WESTERN',
    code: 'A1001',
    name: 'TARKWA NSUAEM',
    voters: 117418,
  },
  {
    region: 'WESTERN',
    code: 'A1101',
    name: 'PRESTEA HUNI-VALLEY',
    voters: 121557,
  },
  {
    region: 'WESTERN',
    code: 'A1201',
    name: 'WASSA AMENFI EAST',
    voters: 79747,
  },
  {
    region: 'WESTERN',
    code: 'A1301',
    name: 'AMENFI CENTRAL',
    voters: 61272,
  },
  {
    region: 'WESTERN',
    code: 'A1401',
    name: 'AMENFI WEST',
    voters: 71365,
  },
  {
    region: 'CENTRAL',
    code: 'B0101',
    name: 'KOMENDA EDINA EGUAFO ABREM',
    voters: 96528,
  },
  {
    region: 'CENTRAL',
    code: 'B0201',
    name: 'CAPE COAST SOUTH',
    voters: 61393,
  },
  {
    region: 'CENTRAL',
    code: 'B0202',
    name: 'CAPE COAST NORTH',
    voters: 65663,
  },
  {
    region: 'CENTRAL',
    code: 'B0301',
    name: 'ABURA/ASEBU/KWAMANKESE',
    voters: 74451,
  },
  {
    region: 'CENTRAL',
    code: 'B0401',
    name: 'MFANTSEMAN',
    voters: 96287,
  },
  {
    region: 'CENTRAL',
    code: 'B0501',
    name: 'EKUMFI',
    voters: 41060,
  },
  {
    region: 'CENTRAL',
    code: 'B0601',
    name: 'AJUMAKO ENYAN ESIAM',
    voters: 75857,
  },
  {
    region: 'CENTRAL',
    code: 'B0701',
    name: 'GOMOA WEST',
    voters: 80341,
  },
  {
    region: 'CENTRAL',
    code: 'B0801',
    name: 'GOMOA CENTRAL',
    voters: 46745,
  },
  {
    region: 'CENTRAL',
    code: 'B0901',
    name: 'GOMOA EAST',
    voters: 63746,
  },
  {
    region: 'CENTRAL',
    code: 'B1001',
    name: 'EFFUTU',
    voters: 59134,
  },
  {
    region: 'CENTRAL',
    code: 'B1101',
    name: 'AWUTU SENYA WEST',
    voters: 79258,
  },
  {
    region: 'CENTRAL',
    code: 'B1201',
    name: 'AWUTU SENYA EAST',
    voters: 109987,
  },
  {
    region: 'CENTRAL',
    code: 'B1301',
    name: 'AGONA WEST',
    voters: 90090,
  },
  {
    region: 'CENTRAL',
    code: 'B1401',
    name: 'AGONA EAST',
    voters: 63281,
  },
  {
    region: 'CENTRAL',
    code: 'B1501',
    name: 'ASIKUMA/ODOBEN/BRAKWA',
    voters: 73817,
  },
  {
    region: 'CENTRAL',
    code: 'B1601',
    name: 'ASSIN CENTRAL',
    voters: 46833,
  },
  {
    region: 'CENTRAL',
    code: 'B1701',
    name: 'ASSIN NORTH',
    voters: 43787,
  },
  {
    region: 'CENTRAL',
    code: 'B1801',
    name: 'ASSIN SOUTH',
    voters: 60866,
  },
  {
    region: 'CENTRAL',
    code: 'B1901',
    name: 'TWIFO ATTI MORKWA',
    voters: 61196,
  },
  {
    region: 'CENTRAL',
    code: 'B2001',
    name: 'HEMANG LOWER DENKYIRA',
    voters: 40802,
  },
  {
    region: 'CENTRAL',
    code: 'B2101',
    name: 'UPPER DENKYIRA EAST',
    voters: 63187,
  },
  {
    region: 'CENTRAL',
    code: 'B2201',
    name: 'UPPER DENKYIRA WEST',
    voters: 44052,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0101',
    name: 'BORTIANOR-NGLESHIE AMANFRO',
    voters: 79713,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0102',
    name: 'DOMEABRA/OBOM',
    voters: 37503,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0201',
    name: 'WEIJA / GBAWE',
    voters: 93410,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0301',
    name: 'ANYAA/SOWUTUOM',
    voters: 123948,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0401',
    name: 'TROBU',
    voters: 117704,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0501',
    name: 'AMASAMAN',
    voters: 92426,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0601',
    name: 'DOME/KWABENYA',
    voters: 144624,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0701',
    name: 'MADINA',
    voters: 121765,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0801',
    name: 'AYAWASO EAST',
    voters: 59003,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C0901',
    name: 'AYAWASO NORTH',
    voters: 57088,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1001',
    name: 'AYAWASO CENTRAL',
    voters: 93169,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1101',
    name: 'AYAWASO WEST WUOGON',
    voters: 92852,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1201',
    name: 'OKAIKWEI SOUTH',
    voters: 99383,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1202',
    name: 'ABLEKUMA SOUTH',
    voters: 87709,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1203',
    name: 'ODODODIODIOO',
    voters: 105056,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1301',
    name: 'OKAIKWEI CENTRAL',
    voters: 69726,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1302',
    name: 'OKAIKWEI NORTH',
    voters: 79641,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1401',
    name: 'ABLEKUMA NORTH',
    voters: 124783,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1501',
    name: 'ABLEKUMA CENTRAL',
    voters: 137154,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1601',
    name: 'ABLEKUMA WEST',
    voters: 92383,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1701',
    name: 'KORLE KLOTTEY',
    voters: 103934,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1801',
    name: 'DADEKOTOPON',
    voters: 124116,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C1901',
    name: 'LEDZOKUKU',
    voters: 142995,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2001',
    name: 'KROWOR',
    voters: 101825,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2101',
    name: 'TEMA EAST',
    voters: 98366,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2102',
    name: 'TEMA CENTRAL',
    voters: 63470,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2201',
    name: 'TEMA-WEST',
    voters: 120258,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2301',
    name: 'KPONE KATAMANSO',
    voters: 101012,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2401',
    name: 'ASHAIMAN',
    voters: 142720,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2501',
    name: 'ADENTAN',
    voters: 110573,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2601',
    name: 'SHAI- OSUDOKU',
    voters: 52831,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2701',
    name: 'NINGO PRAMPRAM',
    voters: 67237,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2801',
    name: 'SEGE',
    voters: 40509,
  },
  {
    region: 'GREATER ACCRA',
    code: 'C2901',
    name: 'ADA',
    voters: 42106,
  },
  {
    region: 'VOLTA',
    code: 'D0101',
    name: 'KETA',
    voters: 55092,
  },
  {
    region: 'VOLTA',
    code: 'D0201',
    name: 'ANLO',
    voters: 60502,
  },
  {
    region: 'VOLTA',
    code: 'D0301',
    name: 'KETU SOUTH',
    voters: 149220,
  },
  {
    region: 'VOLTA',
    code: 'D0401',
    name: 'KETU NORTH',
    voters: 72775,
  },
  {
    region: 'VOLTA',
    code: 'D0501',
    name: 'AKATSI SOUTH',
    voters: 53092,
  },
  {
    region: 'VOLTA',
    code: 'D0601',
    name: 'AKATSI NORTH',
    voters: 23092,
  },
  {
    region: 'VOLTA',
    code: 'D0701',
    name: 'SOUTH TONGU',
    voters: 64449,
  },
  {
    region: 'VOLTA',
    code: 'D0801',
    name: 'CENTRAL TONGU',
    voters: 47368,
  },
  {
    region: 'VOLTA',
    code: 'D0901',
    name: 'NORTH TONGU',
    voters: 59378,
  },
  {
    region: 'VOLTA',
    code: 'D1001',
    name: 'ADAKLU',
    voters: 20606,
  },
  {
    region: 'VOLTA',
    code: 'D1101',
    name: 'AGOTIME-ZIOPE',
    voters: 32531,
  },
  {
    region: 'VOLTA',
    code: 'D1201',
    name: 'HO CENTRAL',
    voters: 104007,
  },
  {
    region: 'VOLTA',
    code: 'D1301',
    name: 'HO WEST',
    voters: 57449,
  },
  {
    region: 'VOLTA',
    code: 'D1401',
    name: 'SOUTH DAYI',
    voters: 32112,
  },
  {
    region: 'VOLTA',
    code: 'D1501',
    name: 'KPANDO',
    voters: 39480,
  },
  {
    region: 'VOLTA',
    code: 'D1601',
    name: 'NORTH DAYI',
    voters: 29225,
  },
  {
    region: 'VOLTA',
    code: 'D1701',
    name: 'HOHOE',
    voters: 58426,
  },
  {
    region: 'VOLTA',
    code: 'D1801',
    name: 'AFADJATO SOUTH',
    voters: 40567,
  },
  {
    region: 'EASTERN',
    code: 'E0101',
    name: 'ASUOGYAMAN',
    voters: 63155,
  },
  {
    region: 'EASTERN',
    code: 'E0201',
    name: 'LOWER MANYA KROBO',
    voters: 72808,
  },
  {
    region: 'EASTERN',
    code: 'E0301',
    name: 'UPPER MANYA KROBO',
    voters: 43503,
  },
  {
    region: 'EASTERN',
    code: 'E0401',
    name: 'YILO KROBO',
    voters: 67371,
  },
  {
    region: 'EASTERN',
    code: 'E0501',
    name: 'NEW JUABEN SOUTH',
    voters: 94634,
  },
  {
    region: 'EASTERN',
    code: 'E0601',
    name: 'NEW JUABEN NORTH',
    voters: 43423,
  },
  {
    region: 'EASTERN',
    code: 'E0701',
    name: 'AKROPONG',
    voters: 67169,
  },
  {
    region: 'EASTERN',
    code: 'E0801',
    name: 'OKERE',
    voters: 35734,
  },
  {
    region: 'EASTERN',
    code: 'E0901',
    name: 'AKUAPEM SOUTH',
    voters: 42747,
  },
  {
    region: 'EASTERN',
    code: 'E1001',
    name: 'NSAWAM/ADOAGYIRI',
    voters: 73399,
  },
  {
    region: 'EASTERN',
    code: 'E1101',
    name: 'SUHUM',
    voters: 73761,
  },
  {
    region: 'EASTERN',
    code: 'E1201',
    name: 'AYENSUANO',
    voters: 57487,
  },
  {
    region: 'EASTERN',
    code: 'E1301',
    name: 'LOWER WEST AKIM',
    voters: 69935,
  },
  {
    region: 'EASTERN',
    code: 'E1401',
    name: 'UPPER WEST AKIM',
    voters: 55785,
  },
  {
    region: 'EASTERN',
    code: 'E1501',
    name: 'AKIM ODA',
    voters: 46473,
  },
  {
    region: 'EASTERN',
    code: 'E1601',
    name: 'ASENE/AKROSO/MANSO',
    voters: 46179,
  },
  {
    region: 'EASTERN',
    code: 'E1701',
    name: 'AKIM SWEDRU',
    voters: 24171,
  },
  {
    region: 'EASTERN',
    code: 'E1801',
    name: 'ACHIASE',
    voters: 34333,
  },
  {
    region: 'EASTERN',
    code: 'E1901',
    name: 'OFOASE/AYIREBI',
    voters: 53685,
  },
  {
    region: 'EASTERN',
    code: 'E2001',
    name: 'KADE',
    voters: 74610,
  },
  {
    region: 'EASTERN',
    code: 'E2101',
    name: 'AKWATIA',
    voters: 55402,
  },
  {
    region: 'EASTERN',
    code: 'E2201',
    name: 'ABIREM',
    voters: 48532,
  },
  {
    region: 'EASTERN',
    code: 'E2301',
    name: 'ABUAKWA SOUTH',
    voters: 55253,
  },
  {
    region: 'EASTERN',
    code: 'E2401',
    name: 'ABUAKWA NORTH',
    voters: 46910,
  },
  {
    region: 'EASTERN',
    code: 'E2501',
    name: 'ATIWA WEST',
    voters: 32074,
  },
  {
    region: 'EASTERN',
    code: 'E2601',
    name: 'ATIWA EAST',
    voters: 34284,
  },
  {
    region: 'EASTERN',
    code: 'E2701',
    name: 'FANTEAKWA NORTH',
    voters: 35103,
  },
  {
    region: 'EASTERN',
    code: 'E2801',
    name: 'FANTEAKWA SOUTH',
    voters: 29101,
  },
  {
    region: 'EASTERN',
    code: 'E2901',
    name: 'NKAWKAW',
    voters: 79652,
  },
  {
    region: 'EASTERN',
    code: 'E3001',
    name: 'MPRAESO',
    voters: 51195,
  },
  {
    region: 'EASTERN',
    code: 'E3101',
    name: 'ABETIFI',
    voters: 52272,
  },
  {
    region: 'EASTERN',
    code: 'E3201',
    name: 'AFRAM PLAINS NORTH',
    voters: 41765,
  },
  {
    region: 'EASTERN',
    code: 'E3301',
    name: 'AFRAM PLAINS SOUTH',
    voters: 37408,
  },
  {
    region: 'ASHANTI',
    code: 'F0101',
    name: 'NEW EDUBIASE',
    voters: 48906,
  },
  {
    region: 'ASHANTI',
    code: 'F0201',
    name: 'AKROFUOM',
    voters: 26124,
  },
  {
    region: 'ASHANTI',
    code: 'F0301',
    name: 'FOMENA',
    voters: 29071,
  },
  {
    region: 'ASHANTI',
    code: 'F0401',
    name: 'ADANSI ASOKWA',
    voters: 43185,
  },
  {
    region: 'ASHANTI',
    code: 'F0501',
    name: 'OBUASI WEST',
    voters: 68541,
  },
  {
    region: 'ASHANTI',
    code: 'F0601',
    name: 'OBUASI EAST',
    voters: 57961,
  },
  {
    region: 'ASHANTI',
    code: 'F0701',
    name: 'BEKWAI',
    voters: 80145,
  },
  {
    region: 'ASHANTI',
    code: 'F0801',
    name: 'BOSOME FREHO',
    voters: 35098,
  },
  {
    region: 'ASHANTI',
    code: 'F0901',
    name: 'ODOTOBIRI',
    voters: 49406,
  },
  {
    region: 'ASHANTI',
    code: 'F1001',
    name: 'MANSO NKWANTA',
    voters: 52734,
  },
  {
    region: 'ASHANTI',
    code: 'F1101',
    name: 'MANSO ADUBIA',
    voters: 49553,
  },
  {
    region: 'ASHANTI',
    code: 'F1201',
    name: 'ATWIMA NWABIAGYA SOUTH',
    voters: 81465,
  },
  {
    region: 'ASHANTI',
    code: 'F1301',
    name: 'ATWIMA NWABIAGYA NORTH',
    voters: 66441,
  },
  {
    region: 'ASHANTI',
    code: 'F1401',
    name: 'ATWIMA MPONUA',
    voters: 84570,
  },
  {
    region: 'ASHANTI',
    code: 'F1501',
    name: 'BOSOMTWE',
    voters: 73041,
  },
  {
    region: 'ASHANTI',
    code: 'F1601',
    name: 'ATWIMA KWANWOMA',
    voters: 86498,
  },
  {
    region: 'ASHANTI',
    code: 'F1701',
    name: 'BANTAMA',
    voters: 81629,
  },
  {
    region: 'ASHANTI',
    code: 'F1702',
    name: 'NHYIAESO',
    voters: 82568,
  },
  {
    region: 'ASHANTI',
    code: 'F1703',
    name: 'MANHYIA SOUTH',
    voters: 56982,
  },
  {
    region: 'ASHANTI',
    code: 'F1704',
    name: 'MANHYIA NORTH',
    voters: 72016,
  },
  {
    region: 'ASHANTI',
    code: 'F1705',
    name: 'SUBIN',
    voters: 86374,
  },
  {
    region: 'ASHANTI',
    code: 'F1801',
    name: 'KWADASO',
    voters: 94035,
  },
  {
    region: 'ASHANTI',
    code: 'F1901',
    name: 'OLD TAFO',
    voters: 80593,
  },
  {
    region: 'ASHANTI',
    code: 'F2001',
    name: 'SUAME',
    voters: 107587,
  },
  {
    region: 'ASHANTI',
    code: 'F2101',
    name: 'ASOKWA',
    voters: 92977,
  },
  {
    region: 'ASHANTI',
    code: 'F2201',
    name: 'OFORIKROM',
    voters: 127082,
  },
  {
    region: 'ASHANTI',
    code: 'F2301',
    name: 'ASAWASE',
    voters: 108321,
  },
  {
    region: 'ASHANTI',
    code: 'F2401',
    name: 'KWABRE EAST',
    voters: 119716,
  },
  {
    region: 'ASHANTI',
    code: 'F2501',
    name: 'AFIGYA KWABRE SOUTH',
    voters: 80242,
  },
  {
    region: 'ASHANTI',
    code: 'F2601',
    name: 'AFIGYA KWABRE NORTH',
    voters: 35045,
  },
  {
    region: 'ASHANTI',
    code: 'F2701',
    name: 'JUABEN',
    voters: 40217,
  },
  {
    region: 'ASHANTI',
    code: 'F2801',
    name: 'EJISU',
    voters: 92564,
  },
  {
    region: 'ASHANTI',
    code: 'F2901',
    name: 'ASANTE AKIM SOUTH',
    voters: 74719,
  },
  {
    region: 'ASHANTI',
    code: 'F3001',
    name: 'ASANTE AKIM CENTRAL',
    voters: 51854,
  },
  {
    region: 'ASHANTI',
    code: 'F3101',
    name: 'ASANTE AKIM NORTH',
    voters: 50908,
  },
  {
    region: 'ASHANTI',
    code: 'F3201',
    name: 'EFFIDUASE / ASOKORE',
    voters: 44019,
  },
  {
    region: 'ASHANTI',
    code: 'F3301',
    name: 'KUMAWU',
    voters: 37746,
  },
  {
    region: 'ASHANTI',
    code: 'F3401',
    name: 'SEKYERE AFRAM PLAINS',
    voters: 15111,
  },
  {
    region: 'ASHANTI',
    code: 'F3501',
    name: 'NSUTA/KWAMANG/BEPOSO',
    voters: 42161,
  },
  {
    region: 'ASHANTI',
    code: 'F3601',
    name: 'MAMPONG',
    voters: 68608,
  },
  {
    region: 'ASHANTI',
    code: 'F3701',
    name: 'EJURA SEKYEDUMASE',
    voters: 68371,
  },
  {
    region: 'ASHANTI',
    code: 'F3801',
    name: 'AFIGYA SEKYERE EAST',
    voters: 70750,
  },
  {
    region: 'ASHANTI',
    code: 'F3901',
    name: 'OFFINSO SOUTH',
    voters: 73753,
  },
  {
    region: 'ASHANTI',
    code: 'F4001',
    name: 'OFFINSO NORTH',
    voters: 51662,
  },
  {
    region: 'ASHANTI',
    code: 'F4101',
    name: 'AHAFO ANO SOUTH WEST',
    voters: 36798,
  },
  {
    region: 'ASHANTI',
    code: 'F4201',
    name: 'AHAFO ANO SOUTH EAST',
    voters: 35457,
  },
  {
    region: 'ASHANTI',
    code: 'F4301',
    name: 'AHAFO ANO NORTH',
    voters: 54964,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0101',
    name: 'AOWIN',
    voters: 80328,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0201',
    name: 'SUAMAN',
    voters: 25584,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0301',
    name: 'BIBIANI-ANHWIASO-BEKWAI',
    voters: 90416,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0401',
    name: 'SEFWI WIAWSO',
    voters: 85857,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0501',
    name: 'SEFWI AKONTOMBRA',
    voters: 44553,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0601',
    name: 'JUABOSO',
    voters: 58479,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0701',
    name: 'BODI',
    voters: 40848,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0801',
    name: 'BIA WEST',
    voters: 73217,
  },
  {
    region: 'WESTERN NORTH',
    code: 'G0901',
    name: 'BIA EAST',
    voters: 32427,
  },
  {
    region: 'AHAFO',
    code: 'H0101',
    name: 'ASUNAFO SOUTH',
    voters: 56798,
  },
  {
    region: 'AHAFO',
    code: 'H0201',
    name: 'ASUNAFO NORTH',
    voters: 79034,
  },
  {
    region: 'AHAFO',
    code: 'H0301',
    name: 'ASUTIFI SOUTH',
    voters: 40755,
  },
  {
    region: 'AHAFO',
    code: 'H0401',
    name: 'ASUTIFI NORTH',
    voters: 42034,
  },
  {
    region: 'AHAFO',
    code: 'H0501',
    name: 'TANO SOUTH',
    voters: 55599,
  },
  {
    region: 'AHAFO',
    code: 'H0601',
    name: 'TANO NORTH',
    voters: 49731,
  },
  {
    region: 'BONO',
    code: 'J0101',
    name: 'SUNYANI EAST',
    voters: 106240,
  },
  {
    region: 'BONO',
    code: 'J0201',
    name: 'SUNYANI WEST',
    voters: 71658,
  },
  {
    region: 'BONO',
    code: 'J0301',
    name: 'DORMAA WEST',
    voters: 26251,
  },
  {
    region: 'BONO',
    code: 'J0401',
    name: 'DORMAA CENTRAL',
    voters: 63155,
  },
  {
    region: 'BONO',
    code: 'J0501',
    name: 'DORMAA EAST',
    voters: 35136,
  },
  {
    region: 'BONO',
    code: 'J0601',
    name: 'BEREKUM EAST',
    voters: 61314,
  },
  {
    region: 'BONO',
    code: 'J0701',
    name: 'BEREKUM WEST',
    voters: 27859,
  },
  {
    region: 'BONO',
    code: 'J0801',
    name: 'JAMAN SOUTH',
    voters: 60271,
  },
  {
    region: 'BONO',
    code: 'J0901',
    name: 'JAMAN NORTH',
    voters: 48702,
  },
  {
    region: 'BONO',
    code: 'J1001',
    name: 'BANDA',
    voters: 17279,
  },
  {
    region: 'BONO',
    code: 'J1101',
    name: 'TAIN',
    voters: 52213,
  },
  {
    region: 'BONO',
    code: 'J1201',
    name: 'WENCHI',
    voters: 63431,
  },
  {
    region: 'BONO EAST',
    code: 'K0101',
    name: 'TECHIMAN',
    voters: 118374,
  },
  {
    region: 'BONO EAST',
    code: 'K0201',
    name: 'KINTAMPO NORTH',
    voters: 66352,
  },
  {
    region: 'BONO EAST',
    code: 'K0301',
    name: 'KINTAMPO SOUTH',
    voters: 45201,
  },
  {
    region: 'BONO EAST',
    code: 'K0401',
    name: 'NKORANZA NORTH',
    voters: 30685,
  },
  {
    region: 'BONO EAST',
    code: 'K0501',
    name: 'NKORANZA SOUTH',
    voters: 64048,
  },
  {
    region: 'BONO EAST',
    code: 'K0601',
    name: 'ATEBUBU/AMANTIN',
    voters: 60750,
  },
  {
    region: 'BONO EAST',
    code: 'K0701',
    name: 'PRU WEST',
    voters: 32075,
  },
  {
    region: 'BONO EAST',
    code: 'K0801',
    name: 'PRU EAST',
    voters: 43932,
  },
  {
    region: 'BONO EAST',
    code: 'K0901',
    name: 'SENE WEST',
    voters: 31638,
  },
  {
    region: 'BONO EAST',
    code: 'K1001',
    name: 'SENE EAST',
    voters: 25409,
  },
  {
    region: 'BONO EAST',
    code: 'K1101',
    name: 'TECHIMAN NORTH',
    voters: 47812,
  },
  {
    region: 'OTI',
    code: 'L0101',
    name: 'BUEM',
    voters: 63898,
  },
  {
    region: 'OTI',
    code: 'L0201',
    name: 'BIAKOYE',
    voters: 45892,
  },
  {
    region: 'OTI',
    code: 'L0301',
    name: 'AKAN',
    voters: 46744,
  },
  {
    region: 'OTI',
    code: 'L0401',
    name: 'KRACHI EAST',
    voters: 48833,
  },
  {
    region: 'OTI',
    code: 'L0501',
    name: 'KRACHI WEST',
    voters: 29652,
  },
  {
    region: 'OTI',
    code: 'L0601',
    name: 'KRACHI-NCHUMURU',
    voters: 36036,
  },
  {
    region: 'OTI',
    code: 'L0701',
    name: 'NKWANTA SOUTH',
    voters: 62400,
  },
  {
    region: 'OTI',
    code: 'L0801',
    name: 'NKWANTA NORTH',
    voters: 53573,
  },
  {
    region: 'NORTHERN',
    code: 'M0101',
    name: 'KPANDAI',
    voters: 56318,
  },
  {
    region: 'NORTHERN',
    code: 'M0201',
    name: 'BIMBILLA',
    voters: 76566,
  },
  {
    region: 'NORTHERN',
    code: 'M0301',
    name: 'WULENSI',
    voters: 42121,
  },
  {
    region: 'NORTHERN',
    code: 'M0401',
    name: 'ZABZUGU',
    voters: 36744,
  },
  {
    region: 'NORTHERN',
    code: 'M0501',
    name: 'TATALE/SANGULI',
    voters: 34956,
  },
  {
    region: 'NORTHERN',
    code: 'M0601',
    name: 'YENDI',
    voters: 72446,
  },
  {
    region: 'NORTHERN',
    code: 'M0701',
    name: 'MION',
    voters: 39337,
  },
  {
    region: 'NORTHERN',
    code: 'M0801',
    name: 'SABOBA',
    voters: 37947,
  },
  {
    region: 'NORTHERN',
    code: 'M0901',
    name: 'GUSHEGU',
    voters: 56061,
  },
  {
    region: 'NORTHERN',
    code: 'M1001',
    name: 'KARAGA',
    voters: 47936,
  },
  {
    region: 'NORTHERN',
    code: 'M1101',
    name: 'SAVELUGU',
    voters: 53359,
  },
  {
    region: 'NORTHERN',
    code: 'M1201',
    name: 'NANTON',
    voters: 27458,
  },
  {
    region: 'NORTHERN',
    code: 'M1301',
    name: 'TAMALE SOUTH',
    voters: 103220,
  },
  {
    region: 'NORTHERN',
    code: 'M1302',
    name: 'TAMALE CENTRAL',
    voters: 86241,
  },
  {
    region: 'NORTHERN',
    code: 'M1401',
    name: 'SAGNARIGU',
    voters: 57695,
  },
  {
    region: 'NORTHERN',
    code: 'M1402',
    name: 'TAMALE NORTH',
    voters: 44956,
  },
  {
    region: 'NORTHERN',
    code: 'M1501',
    name: 'TOLON',
    voters: 60926,
  },
  {
    region: 'NORTHERN',
    code: 'M1601',
    name: 'KUMBUNGU',
    voters: 48127,
  },
  {
    region: 'SAVANNAH',
    code: 'N0101',
    name: 'BOLE/BAMBOI',
    voters: 41323,
  },
  {
    region: 'SAVANNAH',
    code: 'N0201',
    name: 'SAWLA TUNA KALBA',
    voters: 47479,
  },
  {
    region: 'SAVANNAH',
    code: 'N0301',
    name: 'DAMONGO',
    voters: 28087,
  },
  {
    region: 'SAVANNAH',
    code: 'N0401',
    name: 'DABOYA/MANKARIGU',
    voters: 26831,
  },
  {
    region: 'SAVANNAH',
    code: 'N0501',
    name: 'YAPEI-KUSAWGU',
    voters: 60157,
  },
  {
    region: 'SAVANNAH',
    code: 'N0601',
    name: 'SALAGA SOUTH',
    voters: 51492,
  },
  {
    region: 'SAVANNAH',
    code: 'N0701',
    name: 'SALAGA NORTH',
    voters: 17478,
  },
  {
    region: 'UPPER WEST',
    code: 'P0101',
    name: 'WA CENTRAL',
    voters: 87724,
  },
  {
    region: 'UPPER WEST',
    code: 'P0201',
    name: 'WA WEST',
    voters: 49857,
  },
  {
    region: 'UPPER WEST',
    code: 'P0301',
    name: 'WA EAST',
    voters: 40261,
  },
  {
    region: 'UPPER WEST',
    code: 'P0401',
    name: 'NADOWLI/KALEO',
    voters: 42952,
  },
  {
    region: 'UPPER WEST',
    code: 'P0501',
    name: 'DAFFIAMA/BUSSIE/ISSA',
    voters: 22042,
  },
  {
    region: 'UPPER WEST',
    code: 'P0601',
    name: 'JIRAPA',
    voters: 44764,
  },
  {
    region: 'UPPER WEST',
    code: 'P0701',
    name: 'LAMBUSSIE',
    voters: 24442,
  },
  {
    region: 'UPPER WEST',
    code: 'P0801',
    name: 'LAWRA',
    voters: 33059,
  },
  {
    region: 'UPPER WEST',
    code: 'P0901',
    name: 'NANDOM',
    voters: 29906,
  },
  {
    region: 'UPPER WEST',
    code: 'P1001',
    name: 'SISSALA WEST',
    voters: 32522,
  },
  {
    region: 'UPPER WEST',
    code: 'P1101',
    name: 'SISSALA EAST',
    voters: 35027,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0101',
    name: 'WALEWALE',
    voters: 68761,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0201',
    name: 'YAGABA /KUBORI',
    voters: 27825,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0301',
    name: 'NALERIGU / GAMBAGA',
    voters: 72290,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0401',
    name: 'BUNKPURUGU',
    voters: 44609,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0501',
    name: 'YUNYOO',
    voters: 23423,
  },
  {
    region: 'NORTH EAST',
    code: 'Q0601',
    name: 'CHEREPONI',
    voters: 35099,
  },
  {
    region: 'UPPER EAST',
    code: 'R0101',
    name: 'BUILSA SOUTH',
    voters: 21283,
  },
  {
    region: 'UPPER EAST',
    code: 'R0201',
    name: 'BUILSA NORTH',
    voters: 32957,
  },
  {
    region: 'UPPER EAST',
    code: 'R0301',
    name: 'KASSENA/NANKANA EAST',
    voters: 58308,
  },
  {
    region: 'UPPER EAST',
    code: 'R0401',
    name: 'KASSENA/NANKANA WEST',
    voters: 53890,
  },
  {
    region: 'UPPER EAST',
    code: 'R0501',
    name: 'BOLGATANGA CENTRAL',
    voters: 73083,
  },
  {
    region: 'UPPER EAST',
    code: 'R0601',
    name: 'BOLGATANGA EAST',
    voters: 21662,
  },
  {
    region: 'UPPER EAST',
    code: 'R0701',
    name: 'BONGO',
    voters: 60646,
  },
  {
    region: 'UPPER EAST',
    code: 'R0801',
    name: 'TALENSI',
    voters: 47072,
  },
  {
    region: 'UPPER EAST',
    code: 'R0901',
    name: 'NABDAM',
    voters: 23326,
  },
  {
    region: 'UPPER EAST',
    code: 'R1001',
    name: 'BAWKU WEST',
    voters: 67675,
  },
  {
    region: 'UPPER EAST',
    code: 'R1101',
    name: 'BAWKU',
    voters: 69849,
  },
  {
    region: 'UPPER EAST',
    code: 'R1201',
    name: 'PUSIGA',
    voters: 46832,
  },
  {
    region: 'UPPER EAST',
    code: 'R1301',
    name: 'GARU',
    voters: 36503,
  },
  {
    region: 'UPPER EAST',
    code: 'R1401',
    name: 'TEMPANE',
    voters: 47158,
  },
  {
    region: 'UPPER EAST',
    code: 'R1501',
    name: 'BINDURI',
    voters: 38831,
  },
];
